Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "web-dmz"

  # Interface DMZ
  config.vm.network "private_network",
    ip: "172.28.200.10",
    virtualbox__intnet: "dmz"

  # WWW externe
  config.vm.synced_folder "./www", "/var/www/yuki", owner: "www-data", group: "www-data"

  # nginx conf externe
  config.vm.synced_folder "./nginx", "/vagrant-nginx"

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y nginx certbot iproute2

  # Forcer la gateway via le FW (DMZ)
    ip route replace default via 172.28.200.254



    rm -f /etc/nginx/sites-enabled/default
    ln -s /vagrant-nginx/yuki.interface3.be.conf /etc/nginx/sites-enabled/yuki.conf

    nginx -t
    systemctl reload nginx
  SHELL
end
