# coding: utf-8
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false
  config.vm.boot_timeout = 600
#  config.vm.hostname = "ldap-server"
  # MGMT network (host-only)
  config.vm.network "private_network", ip: "172.28.128.110", auto_config: true

  # Interface Servers
  config.vm.network "private_network", ip: "172.28.2.10", virtualbox__intnet: "servers"

  # External config files (prof-style)
  config.vm.provision "file", source: "./files/01-netplan.yaml", destination: "/tmp/01-netplan.yaml"
  config.vm.provision "file", source: "./files/install-krb5.txt", destination: "/home/vagrant/install-krb5.txt"
  config.vm.provision "file", source: "./files/install-slapd.txt", destination: "/home/vagrant/install-slapd.txt"
  config.vm.provision "file", source: "./files/ldap.conf",         destination: "/home/vagrant/ldap.conf"

  config.vm.provision "file", source: "./files/ldifs",   destination: "/home/vagrant/ldifs"
  config.vm.provision "file", source: "./files/secrets", destination: "/home/vagrant/secrets"

  config.vm.provision "shell", path: "./provision.sh"
end
